---
name: 'CI'

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 1,15 * *'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        version: ['bookworm-slim','bookworm','trixie','trixie-slim']
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'docker/setup-qemu-action@v1'
      - uses: 'docker/setup-buildx-action@v1'

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push image'
        uses: 'docker/build-push-action@v6'
        with:
          context: '{{defaultContext}}:Dockerfiles/${{ matrix.version }}/'
          file: 'Dockerfile'
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: 'lacrif/debian-systemd:${{ matrix.version }}'
