---
name: 'CI'

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 1,15 * *'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        version: ['bookworm','trixie']
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'docker/setup-qemu-action@v1'
      - uses: 'docker/setup-buildx-action@v1'

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push image'
        uses: 'docker/build-push-action@v6'
        with:
          context: '{{defaultContext}}:Dockerfiles/${{ matrix.version }}/'
          file: 'Dockerfile'
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: 'lacrif/debian-systemd:${{ matrix.version }}'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'lacrif/debian-systemd:${{ matrix.version }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
